import { Product } from './types';

export const CATEGORIES = ['Men', 'Women', 'Kids', 'Accessories', 'New Arrivals', 'Offers'];

export const HOME_SLIDES = [
  {
    id: 1,
    image: "https://picsum.photos/id/445/1600/800",
    title: "Summer Collection 2025",
    subtitle: "Upgrade your wardrobe with the latest trends this season.",
    btnText: "Shop New Arrivals",
    link: "/category/new%20arrivals",
    align: "center" as const
  },
  {
    id: 2,
    image: "https://picsum.photos/id/1005/1600/800",
    title: "Modern Gentleman",
    subtitle: "Sharp, sophisticated styles for the urban man.",
    btnText: "Browse Men",
    link: "/category/men",
    align: "left" as const
  },
  {
    id: 3,
    image: "https://picsum.photos/id/338/1600/800",
    title: "Elegance Redefined",
    subtitle: "Discover the new era of women's fashion.",
    btnText: "Browse Women",
    link: "/category/women",
    align: "right" as const
  }
];

// Using Picsum with fixed IDs to simulate consistent products
export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Classic White Linen Shirt",
    price: 45,
    discount: 0,
    category: "Men",
    image: "https://picsum.photos/id/1005/800/800",
    images: ["https://picsum.photos/id/1005/800/800", "https://picsum.photos/id/1005/800/800?grayscale"],
    rating: 4.5,
    reviews: 120,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Beige"],
    description: "A breathable, lightweight linen shirt perfect for summer days. Features a relaxed fit and mother-of-pearl buttons.",
    fabric: "100% Linen",
    fit: "Regular",
    care: "Machine wash cold",
    isNew: true,
    tags: ["summer", "casual", "work", "breathable"]
  },
  {
    id: 2,
    name: "Floral Summer Dress",
    price: 89,
    discount: 10,
    category: "Women",
    image: "https://picsum.photos/id/129/800/800",
    images: ["https://picsum.photos/id/129/800/800", "https://picsum.photos/id/338/800/800"],
    rating: 4.8,
    reviews: 85,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Red"],
    description: "Elegant floral print dress with a cinched waist and flowing skirt. Perfect for garden parties.",
    fabric: "Viscose Blend",
    fit: "Slim",
    care: "Hand wash only",
    isNew: true,
    tags: ["party", "summer", "elegant"]
  },
  {
    id: 3,
    name: "Urban Denim Jacket",
    price: 120,
    discount: 20,
    category: "Men",
    image: "https://picsum.photos/id/338/800/800",
    images: ["https://picsum.photos/id/338/800/800", "https://picsum.photos/id/669/800/800"],
    rating: 4.2,
    reviews: 45,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    description: "Rugged denim jacket with vintage wash. Features warm sherpa lining for cooler evenings.",
    fabric: "100% Cotton Denim",
    fit: "Boxy",
    care: "Machine wash warm",
    tags: ["winter", "casual", "outerwear"]
  },
  {
    id: 4,
    name: "Minimalist Leather Bag",
    price: 150,
    discount: 0,
    category: "Accessories",
    image: "https://picsum.photos/id/250/800/800",
    images: ["https://picsum.photos/id/250/800/800"],
    rating: 4.9,
    reviews: 210,
    sizes: ["One Size"],
    colors: ["Brown", "Black"],
    description: "Handcrafted leather tote bag. Spacious enough for a laptop and daily essentials.",
    fabric: "Genuine Leather",
    fit: "N/A",
    care: "Leather cleaner",
    tags: ["work", "travel", "luxury"]
  },
  {
    id: 5,
    name: "Kids Cozy Hoodie",
    price: 35,
    discount: 5,
    category: "Kids",
    image: "https://picsum.photos/id/177/800/800",
    images: ["https://picsum.photos/id/177/800/800"],
    rating: 4.6,
    reviews: 30,
    sizes: ["S", "M", "L"],
    colors: ["Green", "Blue"],
    description: "Soft fleece hoodie for active kids. Durable and warm.",
    fabric: "Cotton Polyester Blend",
    fit: "Relaxed",
    care: "Machine wash tumble dry",
    tags: ["winter", "school", "casual"]
  },
  {
    id: 6,
    name: "Evening Silk Scarf",
    price: 40,
    discount: 50,
    category: "Accessories",
    image: "https://picsum.photos/id/870/800/800",
    images: ["https://picsum.photos/id/870/800/800"],
    rating: 4.3,
    reviews: 12,
    sizes: ["One Size"],
    colors: ["Red", "Gold"],
    description: "Luxurious silk scarf to add a pop of color to any outfit.",
    fabric: "100% Silk",
    fit: "N/A",
    care: "Dry clean only",
    tags: ["formal", "gift"]
  },
  {
    id: 7,
    name: "Active Running Sneakers",
    price: 95,
    discount: 0,
    category: "Men",
    image: "https://picsum.photos/id/103/800/800",
    images: ["https://picsum.photos/id/103/800/800"],
    rating: 4.7,
    reviews: 156,
    sizes: ["8", "9", "10", "11"],
    colors: ["Black", "White"],
    description: "High-performance running shoes with cushioned soles.",
    fabric: "Mesh & Synthetic",
    fit: "True to size",
    care: "Wipe clean",
    tags: ["sports", "gym"]
  },
  {
    id: 8,
    name: "Wool Blend Overcoat",
    price: 220,
    discount: 0,
    category: "Women",
    image: "https://picsum.photos/id/839/800/800",
    images: ["https://picsum.photos/id/839/800/800"],
    rating: 4.9,
    reviews: 67,
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Black"],
    description: "Classic trench style overcoat made from premium wool blend.",
    fabric: "Wool / Polyester",
    fit: "Regular",
    care: "Dry clean",
    tags: ["winter", "formal", "work"]
  }
];