import React, { useState, useContext } from 'react';
import { ShopContext } from '../App';
import { useNavigate } from 'react-router-dom';
import { dispatchLog } from '../services/geminiService';
import { Order } from '../types';
import { orderService } from '../services/orderService';

export const CheckoutPage: React.FC = () => {
    const { cart, clearCart, user, addOrder } = useContext(ShopContext);
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState(false);
    const [orderId, setOrderId] = useState('');

    const [formData, setFormData] = useState({
        firstName: user?.name.split(' ')[0] || '',
        lastName: user?.name.split(' ')[1] || '',
        email: user?.email || '',
        address: '',
        city: '',
        state: '',
        zip: '',
        phone: ''
    });

    const subtotal = cart.reduce((acc, item) => acc + (item.product.price * item.quantity), 0);
    const shipping = subtotal > 1000 ? 0 : 50; // Free shipping over 1000
    const total = subtotal + shipping;

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!user?.id) {
            alert("Please login to place an order.");
            return;
        }
        setLoading(true);

        const newOrder: Order = {
            id: '', // Generated by DB
            date: new Date().toISOString(),
            items: [...cart],
            total: total,
            status: 'Processing',
            paymentMethod: 'Cash on Delivery',
            shippingAddress: formData
        };

        const success = await orderService.createOrder(newOrder, user.id);

        setLoading(false);

        if (success) {
            setOrderId('Confirmed'); // Or get ID from service if returned
            setSuccess(true);
            clearCart();
            dispatchLog('info', 'Order Placed', { total, method: 'COD' });
            window.scrollTo(0, 0);
        } else {
            alert("Failed to place order. Please try again.");
        }
    };

    if (cart.length === 0 && !success) {
        return (
            <div className="max-w-7xl mx-auto px-4 py-20 text-center">
                <div className="mb-6">
                    <svg className="mx-auto h-24 w-24 text-gray-300 dark:text-gray-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                    </svg>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Your cart is empty</h2>
                <p className="text-gray-500 dark:text-gray-400 mb-8">Add some stylish items to your cart to proceed to checkout.</p>
                <button onClick={() => navigate('/')} className="bg-indigo-600 text-white px-8 py-3 rounded-full font-medium hover:bg-indigo-700 transition">
                    Start Shopping
                </button>
            </div>
        );
    }

    if (success) {
        return (
            <div className="max-w-3xl mx-auto px-4 py-16 text-center animate-fade-in-up">
                <div className="w-20 h-20 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mx-auto mb-6">
                    <svg className="w-10 h-10 text-green-600 dark:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                </div>
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Order Placed Successfully!</h1>
                <p className="text-lg text-gray-600 dark:text-gray-300 mb-8">Thank you for your purchase. Your order #{orderId} has been confirmed.</p>

                <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 mb-8 text-left max-w-md mx-auto border border-gray-200 dark:border-gray-700">
                    <h3 className="font-semibold text-gray-900 dark:text-white mb-4 border-b border-gray-200 dark:border-gray-700 pb-2">Order Details</h3>
                    <div className="flex justify-between mb-2 text-sm">
                        <span className="text-gray-600 dark:text-gray-400">Payment Method:</span>
                        <span className="font-medium text-gray-900 dark:text-white">Cash on Delivery</span>
                    </div>
                    <div className="flex justify-between mb-2 text-sm">
                        <span className="text-gray-600 dark:text-gray-400">Total Amount:</span>
                        <span className="font-bold text-indigo-600 dark:text-indigo-400">₹{total.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                        <span className="text-gray-600 dark:text-gray-400">Estimated Delivery:</span>
                        <span className="font-medium text-gray-900 dark:text-white">3-5 Business Days</span>
                    </div>
                </div>

                <div className="flex justify-center gap-4">
                    <button onClick={() => navigate('/orders')} className="bg-indigo-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-indigo-700 transition">
                        View My Orders
                    </button>
                    <button onClick={() => navigate('/')} className="bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 px-6 py-3 rounded-lg font-medium hover:bg-gray-50 dark:hover:bg-gray-700 transition">
                        Continue Shopping
                    </button>
                </div>
            </div>
        )
    }

    return (
        <div className="bg-gray-50 dark:bg-gray-900 min-h-screen py-10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Checkout</h1>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    {/* Left Column - Form */}
                    <div className="lg:col-span-7">
                        <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6 md:p-8">
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
                                <span className="w-8 h-8 rounded-full bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-sm font-bold">1</span>
                                Shipping Address
                            </h2>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">First Name</label>
                                    <input
                                        type="text" name="firstName" required value={formData.firstName} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Last Name</label>
                                    <input
                                        type="text" name="lastName" required value={formData.lastName} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div className="md:col-span-2">
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Email Address</label>
                                    <input
                                        type="email" name="email" required value={formData.email} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div className="md:col-span-2">
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Street Address</label>
                                    <input
                                        type="text" name="address" required value={formData.address} onChange={handleInputChange} placeholder="123 Fashion St"
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">City</label>
                                    <input
                                        type="text" name="city" required value={formData.city} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">State / Province</label>
                                    <input
                                        type="text" name="state" required value={formData.state} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Zip / Postal Code</label>
                                    <input
                                        type="text" name="zip" required value={formData.zip} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Phone Number</label>
                                    <input
                                        type="tel" name="phone" required value={formData.phone} onChange={handleInputChange}
                                        className="w-full rounded-lg border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 focus:ring-indigo-500 focus:border-indigo-500"
                                    />
                                </div>
                            </div>

                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-6 flex items-center gap-2 mt-8">
                                <span className="w-8 h-8 rounded-full bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-sm font-bold">2</span>
                                Payment Method
                            </h2>

                            <div className="space-y-4">
                                <label className="relative flex items-center p-4 rounded-xl border-2 border-indigo-600 bg-indigo-50 dark:bg-indigo-900/20 cursor-pointer">
                                    <input type="radio" name="payment" checked readOnly className="h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-500" />
                                    <div className="ml-3 flex-1">
                                        <span className="block text-sm font-bold text-gray-900 dark:text-white">Cash on Delivery</span>
                                        <span className="block text-xs text-gray-500 dark:text-gray-400">Pay securely when your order arrives.</span>
                                    </div>
                                    <svg className="h-6 w-6 text-indigo-600 dark:text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
                                    </svg>
                                </label>
                                <div className="opacity-50 pointer-events-none relative flex items-center p-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
                                    <input type="radio" name="payment" disabled className="h-4 w-4 text-gray-400 border-gray-300" />
                                    <div className="ml-3 flex-1">
                                        <span className="block text-sm font-medium text-gray-900 dark:text-white">Online Payment (Unavailable)</span>
                                    </div>
                                </div>
                            </div>

                            <button
                                type="submit"
                                disabled={loading}
                                className="mt-8 w-full bg-indigo-600 text-white py-4 rounded-xl font-bold text-lg hover:bg-indigo-700 transition shadow-lg shadow-indigo-200 dark:shadow-none disabled:opacity-70 flex justify-center items-center"
                            >
                                {loading ? (
                                    <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                    </svg>
                                ) : 'Place Order'}
                            </button>
                            <p className="text-center text-xs text-gray-500 mt-4">By placing your order, you agree to our Terms of Service.</p>
                        </form>
                    </div>

                    {/* Right Column - Summary */}
                    <div className="lg:col-span-5">
                        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6 sticky top-24">
                            <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">Order Summary</h2>

                            <ul className="divide-y divide-gray-100 dark:divide-gray-700 mb-6 max-h-96 overflow-y-auto">
                                {cart.map((item) => (
                                    <li key={`${item.product.id}-${item.size}`} className="py-4 flex gap-4">
                                        <img src={item.product.image} alt={item.product.name} className="w-16 h-16 object-cover rounded-md" />
                                        <div className="flex-1">
                                            <h3 className="text-sm font-medium text-gray-900 dark:text-white">{item.product.name}</h3>
                                            <p className="text-xs text-gray-500 dark:text-gray-400">Size: {item.size} | Qty: {item.quantity}</p>
                                        </div>
                                        <div className="text-sm font-medium text-gray-900 dark:text-white">
                                            ₹{(item.product.price * item.quantity).toFixed(2)}
                                        </div>
                                    </li>
                                ))}
                            </ul>

                            <div className="space-y-3 border-t border-gray-100 dark:border-gray-700 pt-4">
                                <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400">
                                    <span>Subtotal</span>
                                    <span>₹{subtotal.toFixed(2)}</span>
                                </div>
                                <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400">
                                    <span>Shipping</span>
                                    <span>{shipping === 0 ? <span className="text-green-600 font-medium">Free</span> : `₹${shipping}`}</span>
                                </div>
                                <div className="flex justify-between text-base font-bold text-gray-900 dark:text-white pt-2 border-t border-gray-100 dark:border-gray-700">
                                    <span>Total</span>
                                    <span>₹{total.toFixed(2)}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};